const LOGIN = "LOGIN";
const UID = "UID"
const ERROR = "ERROR"
const LOGOUT = "LOGOUT"
const LOGOUTFROMPROFILE = "LOGOUTFROMPROFILE"
const GETUSER = "GETUSER"
const USERDETAILS = "USERDETAILS"
const ISLOGIN = "ISLOGIN"
const SETTRUE = "SETTRUE"

export { LOGIN, UID, ERROR, LOGOUT, LOGOUTFROMPROFILE, GETUSER, USERDETAILS, ISLOGIN, SETTRUE }